window.BIRRAS4HEALTH_DATA = {
  "meta": {
    "total": 58,
    "linkedin": 23,
    "categories": 37,
    "locations": 11,
    "top_categories": [
      [
        "Startup",
        10
      ],
      [
        "Hospital",
        5
      ],
      [
        "Ecosistema",
        4
      ],
      [
        "Academia",
        3
      ],
      [
        "Inversión",
        2
      ],
      [
        "Medtech",
        2
      ],
      [
        "Pharma",
        2
      ],
      [
        "Academia / pharma",
        1
      ]
    ],
    "top_locations": [
      [
        "Madrid",
        38
      ],
      [
        "España",
        7
      ],
      [
        "Barcelona",
        5
      ],
      [
        "Alicante",
        1
      ],
      [
        "Alicante / Barcelona",
        1
      ],
      [
        "Colombia / España",
        1
      ],
      [
        "EEUU / Madrid",
        1
      ],
      [
        "Madrid / Barcelona",
        1
      ]
    ]
  },
  "people": [
    {
      "name": "Alejandro Expósito",
      "organization": "Servatrix",
      "role": "Profesional",
      "category": "Startup",
      "area": "Salud digital, innovación",
      "location": "Madrid",
      "linkedin": "",
      "note": "Muy activo en el ecosistema.",
      "slug": "alejandro-exposito",
      "has_linkedin": false,
      "search_blob": "alejandro expósito servatrix profesional startup salud digital, innovación madrid muy activo en el ecosistema."
    },
    {
      "name": "Ana García Poyo",
      "organization": "Bitsphi",
      "role": "Fundadora / directiva",
      "category": "Startup",
      "area": "Neurociencia, pediatría, TDAH",
      "location": "Madrid",
      "linkedin": "",
      "note": "En la intersección entre neurociencia y pediatría.",
      "slug": "ana-garcia-poyo",
      "has_linkedin": false,
      "search_blob": "ana garcía poyo bitsphi fundadora / directiva startup neurociencia, pediatría, tdah madrid en la intersección entre neurociencia y pediatría."
    },
    {
      "name": "Ana Ye",
      "organization": "Ownmed Innovation",
      "role": "Fundadora",
      "category": "Startup",
      "area": "Innovación sanitaria",
      "location": "Madrid",
      "linkedin": "",
      "note": "Perfil emprendedor muy conectado.",
      "slug": "ana-ye",
      "has_linkedin": false,
      "search_blob": "ana ye ownmed innovation fundadora startup innovación sanitaria madrid perfil emprendedor muy conectado."
    },
    {
      "name": "Antonio Díaz",
      "organization": "PCYT / FIPSE",
      "role": "Experto en innovación",
      "category": "Ecosistema",
      "area": "Innovación sanitaria, financiación",
      "location": "Madrid",
      "linkedin": "",
      "note": "Figura veterana en el impulso de innovación.",
      "slug": "antonio-diaz",
      "has_linkedin": false,
      "search_blob": "antonio díaz pcyt / fipse experto en innovación ecosistema innovación sanitaria, financiación madrid figura veterana en el impulso de innovación."
    },
    {
      "name": "Antonio G.R. / Antonio García Romero",
      "organization": "IE Business School",
      "role": "Profesor",
      "category": "Academia",
      "area": "IA, gestión sanitaria, investigación",
      "location": "Madrid",
      "linkedin": "",
      "note": "Referente académico y de debate crítico.",
      "slug": "antonio-g-r-antonio-garcia-romero",
      "has_linkedin": false,
      "search_blob": "antonio g.r. / antonio garcía romero ie business school profesor academia ia, gestión sanitaria, investigación madrid referente académico y de debate crítico."
    },
    {
      "name": "Antonio González",
      "organization": "Vulpix IA / IE",
      "role": "CEO y profesor",
      "category": "Startup / academia",
      "area": "IA médica, emprendimiento",
      "location": "Madrid",
      "linkedin": "",
      "note": "Combina academia y emprendimiento.",
      "slug": "antonio-gonzalez",
      "has_linkedin": false,
      "search_blob": "antonio gonzález vulpix ia / ie ceo y profesor startup / academia ia médica, emprendimiento madrid combina academia y emprendimiento."
    },
    {
      "name": "Antonio Rodríguez",
      "organization": "Hita Ventures / Coral / Cambridge Biocapital",
      "role": "Fundador y dinamizador",
      "category": "Venture builder",
      "area": "Innovación sanitaria, inversión, transferencia tecnológica",
      "location": "Madrid",
      "linkedin": "",
      "note": "Nodo principal del grupo y organizador de encuentros.",
      "slug": "antonio-rodriguez",
      "has_linkedin": false,
      "search_blob": "antonio rodríguez hita ventures / coral / cambridge biocapital fundador y dinamizador venture builder innovación sanitaria, inversión, transferencia tecnológica madrid nodo principal del grupo y organizador de encuentros."
    },
    {
      "name": "Beatriz Gil-Casares",
      "organization": "Hospital del Sureste",
      "role": "Jefa de Sección de Nefrología",
      "category": "Hospital",
      "area": "Nefrología, IA en salud",
      "location": "Madrid",
      "linkedin": "https://www.linkedin.com/in/beatriz-gil-casares-casanova-70975046",
      "note": "Interés claro en IA en salud.",
      "slug": "beatriz-gil-casares",
      "has_linkedin": true,
      "search_blob": "beatriz gil-casares hospital del sureste jefa de sección de nefrología hospital nefrología, ia en salud madrid interés claro en ia en salud."
    },
    {
      "name": "Carlos Bezos",
      "organization": "Instituto de Experiencia del Paciente",
      "role": "Director",
      "category": "Asociación / innovación",
      "area": "Experiencia de paciente, innovación digital",
      "location": "Madrid",
      "linkedin": "",
      "note": "Conecta innovación con experiencia de usuario.",
      "slug": "carlos-bezos",
      "has_linkedin": false,
      "search_blob": "carlos bezos instituto de experiencia del paciente director asociación / innovación experiencia de paciente, innovación digital madrid conecta innovación con experiencia de usuario."
    },
    {
      "name": "Carlos Cosculluela",
      "organization": "Fundación DRO",
      "role": "Director",
      "category": "Ecosistema",
      "area": "Emprendimiento científico",
      "location": "Madrid",
      "linkedin": "",
      "note": "Muy activo en eventos y conexión de perfiles.",
      "slug": "carlos-cosculluela",
      "has_linkedin": false,
      "search_blob": "carlos cosculluela fundación dro director ecosistema emprendimiento científico madrid muy activo en eventos y conexión de perfiles."
    },
    {
      "name": "Carmen (Bitsphi)",
      "organization": "Bitsphi",
      "role": "Miembro del equipo",
      "category": "Startup",
      "area": "Neurociencia, salud digital",
      "location": "Madrid",
      "linkedin": "",
      "note": "Equipo Bitsphi.",
      "slug": "carmen-bitsphi",
      "has_linkedin": false,
      "search_blob": "carmen (bitsphi) bitsphi miembro del equipo startup neurociencia, salud digital madrid equipo bitsphi."
    },
    {
      "name": "Charlie Ruth",
      "organization": "Harvard / patentes / inversión",
      "role": "Abogada y fellow",
      "category": "Inversión / legal",
      "area": "Patentes, fondos internacionales, USA-LATAM",
      "location": "Madrid",
      "linkedin": "https://www.linkedin.com/in/charlieruth",
      "note": "Puente entre EEUU, LATAM y Europa.",
      "slug": "charlie-ruth",
      "has_linkedin": true,
      "search_blob": "charlie ruth harvard / patentes / inversión abogada y fellow inversión / legal patentes, fondos internacionales, usa-latam madrid puente entre eeuu, latam y europa."
    },
    {
      "name": "Christophe",
      "organization": "Consultoría internacional",
      "role": "Consultor",
      "category": "Salud digital",
      "area": "EIT Health, innovación europea",
      "location": "Madrid / Francia",
      "linkedin": "",
      "note": "Perspectiva europea y análisis sectorial.",
      "slug": "christophe",
      "has_linkedin": false,
      "search_blob": "christophe consultoría internacional consultor salud digital eit health, innovación europea madrid / francia perspectiva europea y análisis sectorial."
    },
    {
      "name": "Clément Destoumieux",
      "organization": "Asociación Española de Startups",
      "role": "Chief of Health",
      "category": "Ecosistema",
      "area": "Health startup policy, advisory",
      "location": "Madrid",
      "linkedin": "https://www.linkedin.com/in/clement-destoumieux/",
      "note": "Puente entre startups y política sectorial.",
      "slug": "clement-destoumieux",
      "has_linkedin": true,
      "search_blob": "clément destoumieux asociación española de startups chief of health ecosistema health startup policy, advisory madrid puente entre startups y política sectorial."
    },
    {
      "name": "Cristian Bataller",
      "organization": "SHA Wellness / Sha wellness",
      "role": "Directivo / emprendedor",
      "category": "Wellness / venture builder",
      "area": "Longevidad, venture building",
      "location": "Alicante / Barcelona",
      "linkedin": "https://www.linkedin.com/in/cristian-bataller-1694aa12",
      "note": "Muy bien conectado en longevidad.",
      "slug": "cristian-bataller",
      "has_linkedin": true,
      "search_blob": "cristian bataller sha wellness / sha wellness directivo / emprendedor wellness / venture builder longevidad, venture building alicante / barcelona muy bien conectado en longevidad."
    },
    {
      "name": "Cristian Bataller",
      "organization": "SHA Wellness",
      "role": "Longevidad / venture builder",
      "category": "Wellness",
      "area": "Salud y longevidad",
      "location": "Alicante",
      "linkedin": "https://www.linkedin.com/in/cristian-bataller-1694aa12",
      "note": "Aporta una visión muy internacional.",
      "slug": "cristian-bataller",
      "has_linkedin": true,
      "search_blob": "cristian bataller sha wellness longevidad / venture builder wellness salud y longevidad alicante aporta una visión muy internacional."
    },
    {
      "name": "Daniel González Muñoz",
      "organization": "Nanostine",
      "role": "CEO y fundador",
      "category": "DeepTech",
      "area": "Nanotecnología, recubrimientos biomédicos",
      "location": "España",
      "linkedin": "",
      "note": "Impulsa soluciones para implantes y biosensores.",
      "slug": "daniel-gonzalez-munoz",
      "has_linkedin": false,
      "search_blob": "daniel gonzález muñoz nanostine ceo y fundador deeptech nanotecnología, recubrimientos biomédicos españa impulsa soluciones para implantes y biosensores."
    },
    {
      "name": "Daniel Jiménez",
      "organization": "BioLynx / Harvard",
      "role": "Fundador e investigador",
      "category": "Academia / startup",
      "area": "Talento científico, community building",
      "location": "Madrid / Harvard",
      "linkedin": "https://www.linkedin.com/in/danieljimenezrey",
      "note": "Muy joven, muy activo y con proyección.",
      "slug": "daniel-jimenez",
      "has_linkedin": true,
      "search_blob": "daniel jiménez biolynx / harvard fundador e investigador academia / startup talento científico, community building madrid / harvard muy joven, muy activo y con proyección."
    },
    {
      "name": "Daniel Sánchez Puerto",
      "organization": "Hospital Gregorio Marañón",
      "role": "Coordinador de la Unidad de Innovación",
      "category": "Hospital",
      "area": "Innovación hospitalaria, genética, biotecnología",
      "location": "Madrid",
      "linkedin": "https://www.linkedin.com/in/daniel-sánchez-puerto-genética-biotecnología",
      "note": "Acceso directo a innovación hospitalaria.",
      "slug": "daniel-sanchez-puerto",
      "has_linkedin": true,
      "search_blob": "daniel sánchez puerto hospital gregorio marañón coordinador de la unidad de innovación hospital innovación hospitalaria, genética, biotecnología madrid acceso directo a innovación hospitalaria."
    },
    {
      "name": "Egemen Tavsanci (Ege)",
      "organization": "Raresum",
      "role": "CEO",
      "category": "Startup",
      "area": "IA, enfermedades raras",
      "location": "Barcelona",
      "linkedin": "https://www.linkedin.com/in/egementavsanci",
      "note": "Emprendedor en serie con proyección global.",
      "slug": "egemen-tavsanci-ege",
      "has_linkedin": true,
      "search_blob": "egemen tavsanci (ege) raresum ceo startup ia, enfermedades raras barcelona emprendedor en serie con proyección global."
    },
    {
      "name": "Elena García",
      "organization": "Innovación sanitaria",
      "role": "Directiva",
      "category": "Hospital / administración",
      "area": "Espacios de datos, innovación pública",
      "location": "Madrid",
      "linkedin": "",
      "note": "Muy conectada con proyectos institucionales.",
      "slug": "elena-garcia",
      "has_linkedin": false,
      "search_blob": "elena garcía innovación sanitaria directiva hospital / administración espacios de datos, innovación pública madrid muy conectada con proyectos institucionales."
    },
    {
      "name": "Eric Gracia",
      "organization": "GooVentures / GooApps",
      "role": "Fundador",
      "category": "Venture capital / digital",
      "area": "IA, apps, emprendimiento",
      "location": "Madrid / Barcelona",
      "linkedin": "https://www.linkedin.com/in/ericgarciaordonez",
      "note": "Con experiencia en inversión y producto digital.",
      "slug": "eric-gracia",
      "has_linkedin": true,
      "search_blob": "eric gracia gooventures / gooapps fundador venture capital / digital ia, apps, emprendimiento madrid / barcelona con experiencia en inversión y producto digital."
    },
    {
      "name": "Evrim",
      "organization": "AstraZeneca / Alexion",
      "role": "Sales Force Excellence Lead",
      "category": "Pharma",
      "area": "CRM, comercial pharma, ejecución",
      "location": "Barcelona",
      "linkedin": "",
      "note": "Experiencia multinacional y comercial.",
      "slug": "evrim",
      "has_linkedin": false,
      "search_blob": "evrim astrazeneca / alexion sales force excellence lead pharma crm, comercial pharma, ejecución barcelona experiencia multinacional y comercial."
    },
    {
      "name": "Ezequiel Labarthe",
      "organization": "Datatherapy",
      "role": "CEO",
      "category": "Startup",
      "area": "Biotecnología, datos",
      "location": "Barcelona",
      "linkedin": "",
      "note": "Ciencia de datos aplicada al sector salud.",
      "slug": "ezequiel-labarthe",
      "has_linkedin": false,
      "search_blob": "ezequiel labarthe datatherapy ceo startup biotecnología, datos barcelona ciencia de datos aplicada al sector salud."
    },
    {
      "name": "Gonzalo Fernández Pico",
      "organization": "Independiente",
      "role": "Consultor / product maker AI",
      "category": "Consultoría",
      "area": "Salud digital, IA, formación",
      "location": "Tenerife",
      "linkedin": "https://www.linkedin.com/in/gonzalofernandezpico",
      "note": "Enfoque práctico en producto e IA.",
      "slug": "gonzalo-fernandez-pico",
      "has_linkedin": true,
      "search_blob": "gonzalo fernández pico independiente consultor / product maker ai consultoría salud digital, ia, formación tenerife enfoque práctico en producto e ia."
    },
    {
      "name": "Gonzalo Fernández-Miranda",
      "organization": "CureAge Therapeutics",
      "role": "CEO",
      "category": "Biotech",
      "area": "Terapias avanzadas, biotecnología",
      "location": "Madrid",
      "linkedin": "https://www.linkedin.com/in/gonzalo-fernandez-miranda",
      "note": "Perfil biotech muy relevante.",
      "slug": "gonzalo-fernandez-miranda",
      "has_linkedin": true,
      "search_blob": "gonzalo fernández-miranda cureage therapeutics ceo biotech terapias avanzadas, biotecnología madrid perfil biotech muy relevante."
    },
    {
      "name": "Gonzalo Martín",
      "organization": "Independiente",
      "role": "Analista / consultor",
      "category": "Estrategia",
      "area": "IA, regulación, mercado",
      "location": "Madrid",
      "linkedin": "",
      "note": "Muy activo en debates sobre regulación.",
      "slug": "gonzalo-martin",
      "has_linkedin": false,
      "search_blob": "gonzalo martín independiente analista / consultor estrategia ia, regulación, mercado madrid muy activo en debates sobre regulación."
    },
    {
      "name": "Ismael Ávila",
      "organization": "Hospital del Mar / EIT Health",
      "role": "Responsable de transferencia de tecnología",
      "category": "Hospital / ecosistema",
      "area": "Tech transfer, innovación, networking",
      "location": "Barcelona",
      "linkedin": "https://www.linkedin.com/in/ismael-avila",
      "note": "Conector fuerte en EIT Health.",
      "slug": "ismael-avila",
      "has_linkedin": true,
      "search_blob": "ismael ávila hospital del mar / eit health responsable de transferencia de tecnología hospital / ecosistema tech transfer, innovación, networking barcelona conector fuerte en eit health."
    },
    {
      "name": "J. A. A. Vega",
      "organization": "Focus Lab Accelerator",
      "role": "Inversor / creador de vehículo",
      "category": "Venture capital",
      "area": "B2B SaaS pre-seed",
      "location": "Madrid",
      "linkedin": "",
      "note": "Apoya compañías pre-seed con enfoque híbrido.",
      "slug": "j-a-a-vega",
      "has_linkedin": false,
      "search_blob": "j. a. a. vega focus lab accelerator inversor / creador de vehículo venture capital b2b saas pre-seed madrid apoya compañías pre-seed con enfoque híbrido."
    },
    {
      "name": "Javier Milagro",
      "organization": "Corify Care",
      "role": "Directivo / fundador",
      "category": "Medtech",
      "area": "Cardiología, tecnología médica",
      "location": "España",
      "linkedin": "",
      "note": "Empresa medtech muy reconocida.",
      "slug": "javier-milagro",
      "has_linkedin": false,
      "search_blob": "javier milagro corify care directivo / fundador medtech cardiología, tecnología médica españa empresa medtech muy reconocida."
    },
    {
      "name": "Jimena Pérez",
      "organization": "CNIC / ex GSK",
      "role": "Investigadora",
      "category": "Academia / pharma",
      "area": "Biomedicina, investigación traslacional",
      "location": "Madrid",
      "linkedin": "https://www.linkedin.com/in/jimena-perez-santos",
      "note": "Perfil en transición hacia emprendimiento.",
      "slug": "jimena-perez",
      "has_linkedin": true,
      "search_blob": "jimena pérez cnic / ex gsk investigadora academia / pharma biomedicina, investigación traslacional madrid perfil en transición hacia emprendimiento."
    },
    {
      "name": "Joan Grasas",
      "organization": "ICS / Debios Diagnostics",
      "role": "Coordinador de innovación y tech transfer",
      "category": "Hospital / startup",
      "area": "Transferencia tecnológica, nefrología, urología",
      "location": "Barcelona",
      "linkedin": "https://www.linkedin.com/in/joan-grasas/",
      "note": "Puente entre hospital, emprendimiento e inversión.",
      "slug": "joan-grasas",
      "has_linkedin": true,
      "search_blob": "joan grasas ics / debios diagnostics coordinador de innovación y tech transfer hospital / startup transferencia tecnológica, nefrología, urología barcelona puente entre hospital, emprendimiento e inversión."
    },
    {
      "name": "Jorge García Rojas (JGR)",
      "organization": "Consultoría pharma",
      "role": "Consultor",
      "category": "Pharma",
      "area": "Pharma, estrategia, desarrollo",
      "location": "Madrid",
      "linkedin": "https://www.linkedin.com/in/jorge-garcía-rojas-b32b7b11b",
      "note": "Ex Janssen / ex GSK.",
      "slug": "jorge-garcia-rojas-jgr",
      "has_linkedin": true,
      "search_blob": "jorge garcía rojas (jgr) consultoría pharma consultor pharma pharma, estrategia, desarrollo madrid ex janssen / ex gsk."
    },
    {
      "name": "José Luis Kunsen",
      "organization": "Kunsen",
      "role": "Socio",
      "category": "Inversión / aceleración",
      "area": "Healthtech, regulación, CROs",
      "location": "Madrid",
      "linkedin": "",
      "note": "Muy activo en dealflow y networking.",
      "slug": "jose-luis-kunsen",
      "has_linkedin": false,
      "search_blob": "josé luis kunsen kunsen socio inversión / aceleración healthtech, regulación, cros madrid muy activo en dealflow y networking."
    },
    {
      "name": "Juan Casado",
      "organization": "Independiente",
      "role": "Inversor / consultor",
      "category": "Inversión",
      "area": "Transferencia, IA, oportunidades de inversión",
      "location": "Madrid",
      "linkedin": "",
      "note": "Comparte oportunidades y contactos útiles.",
      "slug": "juan-casado",
      "has_linkedin": false,
      "search_blob": "juan casado independiente inversor / consultor inversión transferencia, ia, oportunidades de inversión madrid comparte oportunidades y contactos útiles."
    },
    {
      "name": "Lola Pérez Garre",
      "organization": "CNIO",
      "role": "Innovation Manager",
      "category": "Centro de investigación",
      "area": "Transferencia tecnológica, oncología",
      "location": "Madrid",
      "linkedin": "",
      "note": "Perfil muy útil para tech transfer en cáncer.",
      "slug": "lola-perez-garre",
      "has_linkedin": false,
      "search_blob": "lola pérez garre cnio innovation manager centro de investigación transferencia tecnológica, oncología madrid perfil muy útil para tech transfer en cáncer."
    },
    {
      "name": "Magdalena Abad",
      "organization": "Hospital La Paz / IDIPAZ",
      "role": "Médico adjunto en Ginecología",
      "category": "Hospital",
      "area": "Ginecología, innovación, investigación",
      "location": "Madrid",
      "linkedin": "",
      "note": "Muy activa en proyectos de innovación.",
      "slug": "magdalena-abad",
      "has_linkedin": false,
      "search_blob": "magdalena abad hospital la paz / idipaz médico adjunto en ginecología hospital ginecología, innovación, investigación madrid muy activa en proyectos de innovación."
    },
    {
      "name": "Manolo Castellano",
      "organization": "Talento Científico / Coral",
      "role": "Fundador / podcaster",
      "category": "Talento",
      "area": "Recruitment científico, liderazgo",
      "location": "España",
      "linkedin": "https://www.linkedin.com/in/manuelcastellanomunoz",
      "note": "Muy útil para talento y cultura de equipo.",
      "slug": "manolo-castellano",
      "has_linkedin": true,
      "search_blob": "manolo castellano talento científico / coral fundador / podcaster talento recruitment científico, liderazgo españa muy útil para talento y cultura de equipo."
    },
    {
      "name": "Mariano DINAMIZA",
      "organization": "DINAMIZA / RETECH",
      "role": "Consultor y dinamizador",
      "category": "Ecosistema",
      "area": "Aceleración, innovación pública",
      "location": "Madrid",
      "linkedin": "",
      "note": "Impulsa quedadas y programas públicos.",
      "slug": "mariano-dinamiza",
      "has_linkedin": false,
      "search_blob": "mariano dinamiza dinamiza / retech consultor y dinamizador ecosistema aceleración, innovación pública madrid impulsa quedadas y programas públicos."
    },
    {
      "name": "Marissa Jiménez",
      "organization": "HM Hospitales",
      "role": "Marketing lead",
      "category": "Hospital",
      "area": "Marketing sanitario, captación de pacientes",
      "location": "Madrid",
      "linkedin": "",
      "note": "Experiencia sanitaria internacional.",
      "slug": "marissa-jimenez",
      "has_linkedin": false,
      "search_blob": "marissa jiménez hm hospitales marketing lead hospital marketing sanitario, captación de pacientes madrid experiencia sanitaria internacional."
    },
    {
      "name": "María Cantos",
      "organization": "GestaVerso",
      "role": "Fundadora / CEO",
      "category": "Startup",
      "area": "Simulación del parto, women's health",
      "location": "Madrid",
      "linkedin": "",
      "note": "Foco en experiencia y preparación del parto.",
      "slug": "maria-cantos",
      "has_linkedin": false,
      "search_blob": "maría cantos gestaverso fundadora / ceo startup simulación del parto, women's health madrid foco en experiencia y preparación del parto."
    },
    {
      "name": "María Ángeles Moreno",
      "organization": "IE Business School",
      "role": "Directora de programa",
      "category": "Academia",
      "area": "Gestión sanitaria",
      "location": "Madrid",
      "linkedin": "",
      "note": "Perfil académico y directivo.",
      "slug": "maria-angeles-moreno",
      "has_linkedin": false,
      "search_blob": "maría ángeles moreno ie business school directora de programa academia gestión sanitaria madrid perfil académico y directivo."
    },
    {
      "name": "Matias",
      "organization": "1MED",
      "role": "Senior Director Business Development",
      "category": "CRO",
      "area": "Ensayos clínicos, regulatoria, CROs",
      "location": "España",
      "linkedin": "",
      "note": "Muy útil para ensayos clínicos y ventas.",
      "slug": "matias",
      "has_linkedin": false,
      "search_blob": "matias 1med senior director business development cro ensayos clínicos, regulatoria, cros españa muy útil para ensayos clínicos y ventas."
    },
    {
      "name": "Mercedes Avilés",
      "organization": "CDTI",
      "role": "Coordinadora de compra pública",
      "category": "Administración",
      "area": "Compra pública innovadora, patentes",
      "location": "Madrid",
      "linkedin": "https://www.linkedin.com/in/mercedes-avil%C3%A9s-07842848",
      "note": "Clave para entender financiación pública.",
      "slug": "mercedes-aviles",
      "has_linkedin": true,
      "search_blob": "mercedes avilés cdti coordinadora de compra pública administración compra pública innovadora, patentes madrid clave para entender financiación pública."
    },
    {
      "name": "Narella Rodríguez-Salamanca",
      "organization": "Investigación clínica",
      "role": "Profesional senior",
      "category": "CRO / clínica",
      "area": "Investigación clínica",
      "location": "Colombia / España",
      "linkedin": "",
      "note": "22 años de experiencia en investigación clínica.",
      "slug": "narella-rodriguez-salamanca",
      "has_linkedin": false,
      "search_blob": "narella rodríguez-salamanca investigación clínica profesional senior cro / clínica investigación clínica colombia / españa 22 años de experiencia en investigación clínica."
    },
    {
      "name": "Nati Chichón",
      "organization": "Mential",
      "role": "Directiva",
      "category": "Startup",
      "area": "Salud mental / gestión",
      "location": "España",
      "linkedin": "",
      "note": "Perfil emprendedor y muy conectado.",
      "slug": "nati-chichon",
      "has_linkedin": false,
      "search_blob": "nati chichón mential directiva startup salud mental / gestión españa perfil emprendedor y muy conectado."
    },
    {
      "name": "Nicolas Medellin",
      "organization": "Embajada de Colombia",
      "role": "Director de negocios y alianzas",
      "category": "Institucional",
      "area": "Biotech, políticas públicas, LATAM",
      "location": "Madrid",
      "linkedin": "",
      "note": "Puente institucional con Colombia.",
      "slug": "nicolas-medellin",
      "has_linkedin": false,
      "search_blob": "nicolas medellin embajada de colombia director de negocios y alianzas institucional biotech, políticas públicas, latam madrid puente institucional con colombia."
    },
    {
      "name": "Pablo Hernández",
      "organization": "Avisania Lab",
      "role": "Cofundador",
      "category": "Startup",
      "area": "Medicina, innovación clínica",
      "location": "España",
      "linkedin": "https://www.linkedin.com/in/pabherher19",
      "note": "Anestesista y emprendedor.",
      "slug": "pablo-hernandez",
      "has_linkedin": true,
      "search_blob": "pablo hernández avisania lab cofundador startup medicina, innovación clínica españa anestesista y emprendedor."
    },
    {
      "name": "Pablo Ramírez",
      "organization": "URJC / Vivero de Empresas de Móstoles",
      "role": "Director",
      "category": "Emprendimiento",
      "area": "Incubación y apoyo a empresas",
      "location": "Madrid",
      "linkedin": "",
      "note": "Conecta universidad y emprendimiento.",
      "slug": "pablo-ramirez",
      "has_linkedin": false,
      "search_blob": "pablo ramírez urjc / vivero de empresas de móstoles director emprendimiento incubación y apoyo a empresas madrid conecta universidad y emprendimiento."
    },
    {
      "name": "Pedro Pereda",
      "organization": "Hemasoft",
      "role": "Fundador",
      "category": "Health IT",
      "area": "Software para bancos de sangre",
      "location": "España",
      "linkedin": "",
      "note": "Fundador histórico del sector.",
      "slug": "pedro-pereda",
      "has_linkedin": false,
      "search_blob": "pedro pereda hemasoft fundador health it software para bancos de sangre españa fundador histórico del sector."
    },
    {
      "name": "Rafael Sáenz de Tejada",
      "organization": "Ysium Medical Innovation",
      "role": "Business Developer",
      "category": "Medtech",
      "area": "Financiación, desarrollo de negocio",
      "location": "Madrid",
      "linkedin": "https://www.linkedin.com/in/rafaelsaenzdetejada",
      "note": "Buscando financiación y crecimiento.",
      "slug": "rafael-saenz-de-tejada",
      "has_linkedin": true,
      "search_blob": "rafael sáenz de tejada ysium medical innovation business developer medtech financiación, desarrollo de negocio madrid buscando financiación y crecimiento."
    },
    {
      "name": "Rafael Terán",
      "organization": "SmartBioAnalytics",
      "role": "General Manager",
      "category": "Startup",
      "area": "Biotech, diagnóstico, desarrollo de negocio",
      "location": "Madrid",
      "linkedin": "",
      "note": "Perfil comercial y científico en salud.",
      "slug": "rafael-teran",
      "has_linkedin": false,
      "search_blob": "rafael terán smartbioanalytics general manager startup biotech, diagnóstico, desarrollo de negocio madrid perfil comercial y científico en salud."
    },
    {
      "name": "Rubén Nieto",
      "organization": "Hospital 12 de Octubre",
      "role": "Responsable de innovación",
      "category": "Hospital",
      "area": "Salud digital, spin-offs, venture building",
      "location": "Madrid",
      "linkedin": "https://www.linkedin.com/in/rubennietolopez",
      "note": "Bioingeniero con amplia experiencia emprendedora.",
      "slug": "ruben-nieto",
      "has_linkedin": true,
      "search_blob": "rubén nieto hospital 12 de octubre responsable de innovación hospital salud digital, spin-offs, venture building madrid bioingeniero con amplia experiencia emprendedora."
    },
    {
      "name": "Ted Yang",
      "organization": "MIT / emprendedor e inversor",
      "role": "Founder / speaker",
      "category": "Inversión",
      "area": "IA, emprendimiento tecnológico",
      "location": "EEUU / Madrid",
      "linkedin": "https://www.linkedin.com/in/tedsensei",
      "note": "Red internacional y experiencia en IA.",
      "slug": "ted-yang",
      "has_linkedin": true,
      "search_blob": "ted yang mit / emprendedor e inversor founder / speaker inversión ia, emprendimiento tecnológico eeuu / madrid red internacional y experiencia en ia."
    },
    {
      "name": "Trini (Trinidad de Frutos)",
      "organization": "Cardia (by Apolo)",
      "role": "Directora de investigación",
      "category": "Pharma / startup",
      "area": "Investigación clínica, pharma",
      "location": "Madrid",
      "linkedin": "",
      "note": "Perfil mixto entre pharma y startup.",
      "slug": "trini-trinidad-de-frutos",
      "has_linkedin": false,
      "search_blob": "trini (trinidad de frutos) cardia (by apolo) directora de investigación pharma / startup investigación clínica, pharma madrid perfil mixto entre pharma y startup."
    },
    {
      "name": "Vittorio Lucat (Don Vito)",
      "organization": "Factory14 (ex)",
      "role": "Operador y startup builder",
      "category": "Startup / growth",
      "area": "Escalado, tech, salud digital",
      "location": "Madrid",
      "linkedin": "https://www.linkedin.com/in/vittorio-lucat",
      "note": "Experiencia en grandes startups y Big Tech.",
      "slug": "vittorio-lucat-don-vito",
      "has_linkedin": true,
      "search_blob": "vittorio lucat (don vito) factory14 (ex) operador y startup builder startup / growth escalado, tech, salud digital madrid experiencia en grandes startups y big tech."
    },
    {
      "name": "Xiang Weng",
      "organization": "Independiente",
      "role": "Profesional",
      "category": "Innovación",
      "area": "Networking internacional",
      "location": "Madrid",
      "linkedin": "https://www.linkedin.com/in/xianweng",
      "note": "Perfil internacional y abierto a colaborar.",
      "slug": "xiang-weng",
      "has_linkedin": true,
      "search_blob": "xiang weng independiente profesional innovación networking internacional madrid perfil internacional y abierto a colaborar."
    },
    {
      "name": "Yolanda Cerezo",
      "organization": "Universidad Francisco de Vitoria",
      "role": "Profesora",
      "category": "Academia",
      "area": "Innovación y salud",
      "location": "Madrid",
      "linkedin": "",
      "note": "Aporta visión universitaria.",
      "slug": "yolanda-cerezo",
      "has_linkedin": false,
      "search_blob": "yolanda cerezo universidad francisco de vitoria profesora academia innovación y salud madrid aporta visión universitaria."
    }
  ],
  "categories": {
    "Startup": 10,
    "Ecosistema": 4,
    "Academia": 3,
    "Startup / academia": 1,
    "Venture builder": 1,
    "Hospital": 5,
    "Asociación / innovación": 1,
    "Inversión / legal": 1,
    "Salud digital": 1,
    "Wellness / venture builder": 1,
    "Wellness": 1,
    "DeepTech": 1,
    "Academia / startup": 1,
    "Hospital / administración": 1,
    "Venture capital / digital": 1,
    "Pharma": 2,
    "Consultoría": 1,
    "Biotech": 1,
    "Estrategia": 1,
    "Hospital / ecosistema": 1,
    "Venture capital": 1,
    "Medtech": 2,
    "Academia / pharma": 1,
    "Hospital / startup": 1,
    "Inversión / aceleración": 1,
    "Inversión": 2,
    "Centro de investigación": 1,
    "Talento": 1,
    "CRO": 1,
    "Administración": 1,
    "CRO / clínica": 1,
    "Institucional": 1,
    "Emprendimiento": 1,
    "Health IT": 1,
    "Pharma / startup": 1,
    "Startup / growth": 1,
    "Innovación": 1
  },
  "locations": {
    "Madrid": 38,
    "Madrid / Francia": 1,
    "Alicante / Barcelona": 1,
    "Alicante": 1,
    "España": 7,
    "Madrid / Harvard": 1,
    "Barcelona": 5,
    "Madrid / Barcelona": 1,
    "Tenerife": 1,
    "Colombia / España": 1,
    "EEUU / Madrid": 1
  }
};
